name: Build packages on release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build
        run: >-
          python -m build

      - run: echo "::set-output name=whl_file::$(basename $(ls dist/*.whl))"
        id: whl_file

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Release ${{ github.ref }}"
          tag_name: ${{ github.ref }}
          body: ""
          #body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "dist/${{ steps.whl_file.outputs.whl_file }}"
          asset_name: ${{ steps.whl_file.outputs.whl_file }}
          asset_content_type: application/zip
